### PR TITLE
"retries", "skiperror", "delete" features & config options added

### PR DESCRIPTION
**Pull request by roadt**
retries: 3                      # retry 3 times if fail to download a gem, optional, def is 1. (no retry)
    delete: false                 # option to control whether delete gems (if remote ones are removed),optional, default is false. 
    skiperror: true              # control whether script skips error, optional, def is true. set it to false, script will stop at error.

### CODE REVIEW

**Comment by sebi** [comment]
Did the style changes in https://github.com/sebi/rubygems-mirror. How can I get this merged?

**Comment by thedeco** [comment]
+1 @berniedurfee same here...still an issue after more than a year...

**Comment by raggi** [comment]
@sebi - open a PR please

**Comment by sebi** [comment]
@raggi Opened a PR under #35

**Pull request merged**
