### PR TITLE
Retries, Skiperror and Delete feature (continuation of #16)

### PR DESCRIPTION
**Pull request by sebi**
This is the continuation of pull request #16 with the requested style changes.

### CODE REVIEW

**Comment by raggi** [comment]
"We can’t automatically merge this pull request."

Would you mind merging/rebasing?

**Comment by sebi** [comment]
Phew. Hope I got this right. If not, please just tell me. I'll do my best ;)

**Comment by thedeco** [comment]
+1

**Comment by sebi** [comment]
@raggi

**Comment by raggi** [comment]
Thanks!!!

**Comment by raggi** [comment]
:cake:

**Pull request merged**
